### ISSUE TITLE
Map art style's attribution

### ISSUE THREAD

**Issue by bruhnild** [Viglino/geoservice-style#1]
Is there any attribution for this json style map ? https://viglino.github.io/geoservice-style/?lon=4.853070&lat=45.751671&z=17.2&layer=mapart

**Comment by Viglino** [comment]
Vector tiles are from IGN-France or IGN-Géoservices / Open licence (I should mention)
See: https://geoservices.ign.fr/documentation/services/api-et-services-ogc/tuiles-vectorielles-tmswmts
or here: https://geoservices.ign.fr/presentation

JSON style is MIT, you don't have to attribute.
